from __future__ import annotations

from .file_extractors import build_data_url, extract_text_from_file
from .llm_generation import (
    analytics_from_qa_logs,
    ask_course_assistant,
    assignment_review_preview,
    datetime_now,
    generate_lesson_pack,
    generate_material_update,
    generate_weakness_analysis,
    student_qa,
)
from .llm_runtime import (
    ARK_API_KEY,
    ARK_BASE_URL,
    ARK_MODEL_TEXT,
    ARK_MODEL_VISION,
    DASHSCOPE_API_KEY,
    DASHSCOPE_BASE_URL,
    DASHSCOPE_MODEL_TEXT,
    DASHSCOPE_MODEL_VISION,
    DEFAULT_API_KEY,
    DEFAULT_BASE_URL,
    DEFAULT_MODEL_FAST,
    DEFAULT_MODEL_SMART,
    FALLBACK_NOTES,
    LLM_TIMEOUT,
    MODEL_DESCRIPTIONS,
    _build_default_model_entries,
    _call_chat_model,
    _clean_answer_text,
    _dedupe_answer_body,
    _dedupe_text_parts,
    _env,
    _extract_json,
    _format_model_label,
    _get_http_client,
    _get_model_config,
    _infer_default_provider,
    _model_catalog,
    _norm_compare_text,
    _normalize_chat_endpoint,
    _truncate,
    list_available_models,
)
